# Generated by Django 4.1.7 on 2023-03-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
