# Generated by Django 4.1.7 on 2023-03-01 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_alter_semester_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='no',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
