# Generated by Django 4.1.7 on 2023-03-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_programpendidikan'),
    ]

    operations = [
        migrations.CreateModel(
            name='GedungKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
    ]
