# Generated by Django 4.1.7 on 2023-03-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_gedungkuliah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pemberitahuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('sub_judul', models.CharField(max_length=255)),
                ('detail', models.TextField(null=True)),
                ('tanggal_terbit', models.DateField(auto_now_add=True)),
                ('tanggal_hapus', models.DateField(null=True)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('file', models.FileField(null=True, upload_to='')),
                ('link', models.URLField(null=True)),
            ],
        ),
    ]
