# Generated by Django 4.1.7 on 2023-03-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_upttik'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('kode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prodi_list', to='academic.jurusan')),
                ('program_pendidikan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prodi_list', to='academic.programpendidikan')),
            ],
        ),
    ]
