# Generated by Django 4.1.7 on 2023-03-02 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0009_programstudi'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProdi',
            fields=[
                ('nip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('no_hp', models.CharField(max_length=255)),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_prodi_list', to='academic.programstudi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
