# Generated by Django 4.1.7 on 2023-03-02 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_staffprodi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('nip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('no_hp', models.CharField(max_length=13)),
                ('gelar', models.CharField(max_length=20)),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.programstudi')),
            ],
        ),
    ]
