# Generated by Django 4.1.7 on 2023-03-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_dosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huruf', models.CharField(max_length=1)),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kelas_list', to='academic.programstudi')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kelas_list', to='academic.semester')),
            ],
        ),
    ]
