# Generated by Django 4.1.7 on 2023-03-06 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_aduanruangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PemberitahuanProdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pemberitahuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_prodi', to='academic.pemberitahuan')),
                ('prodi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemberitahuan_list', to='academic.programstudi')),
            ],
        ),
    ]
