# Generated by Django 4.1.7 on 2023-03-06 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_pemberitahuanprodi'),
    ]

    operations = [
        migrations.CreateModel(
            name='PemberitahuanJurusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemberitahuan_list', to='academic.jurusan')),
                ('pemberitahuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_jurusan', to='academic.pemberitahuan')),
            ],
        ),
    ]
