# Generated by Django 4.1.7 on 2023-03-07 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0017_pemberitahuanjurusan'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaryaIlmiah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('abstrak', models.TextField(null=True)),
                ('tanggal_terbit', models.DateField(auto_now_add=True)),
                ('link_versi_full', models.URLField(null=True)),
                ('tipe', models.CharField(choices=[('LM', 'Laporan Magang'), ('TA', 'Tugas Akhir'), ('S', 'Skripsi'), ('PTA', 'Proposal Tugas Akhir'), ('PS', 'Proposal Skripsi')], max_length=3)),
                ('file_preview', models.FileField(upload_to='')),
                ('mahasiswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karya_ilmiah_list', to='academic.mahasiswa')),
                ('prodi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karya_ilmiah_list', to='academic.programstudi')),
            ],
        ),
    ]
