# Generated by Django 4.1.7 on 2023-03-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0019_jadwal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=255, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('jumlah_teori', models.PositiveSmallIntegerField()),
                ('jumlah_pratikum', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
