# Generated by Django 4.1.7 on 2023-03-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0020_matakuliah'),
    ]

    operations = [
        migrations.CreateModel(
            name='jadwalMakul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('hari', models.CharField(choices=[('S', 'Senin'), ('SE', 'Selasa'), ('R', 'Rabu'), ('K', 'Kamis'), ('J', 'Jumat')], default='S', max_length=2)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='makul_ajar', to='academic.dosen')),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makul_list', to='academic.jadwal')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.matakuliah')),
                ('ruangan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.ruangan')),
            ],
            options={
                'unique_together': {('jam_mulai', 'jam_selesai', 'hari', 'ruangan')},
            },
        ),
    ]
