# Generated by Django 4.1.7 on 2023-03-10 03:30

from django.db import migrations
from django.db import connection


def copy_data(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("INSERT INTO academic_tempupttik (no_induk, no_hp, user_id) SELECT nip, no_hp, user_id FROM academic_upttik")


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0024_tempupttik'),
    ]

    operations = [
        migrations.RunPython(copy_data),
    ]
