# Generated by Django 4.1.7 on 2023-03-13 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0029_copy_data_programstudi_to_tempprogramstudi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='temp_program_studi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academic.tempprogramstudi'),
        ),
        migrations.AddField(
            model_name='karyailmiah',
            name='temp_program_studi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.tempprogramstudi'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='temp_program_studi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academic.tempprogramstudi'),
        ),
        migrations.AddField(
            model_name='pemberitahuanprodi',
            name='temp_program_studi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.tempprogramstudi'),
        ),
        migrations.AddField(
            model_name='staffprodi',
            name='temp_program_studi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.tempprogramstudi'),
        ),
    ]
