# Generated by Django 4.1.7 on 2023-03-13 04:02

from django.db import migrations, connection


def assign_data(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('''
        UPDATE academic_dosen d
        JOIN academic_tempprogramstudi tps ON d.prodi_id = tps.kode
        SET d.temp_program_studi_id = tps.id;

        UPDATE academic_karyailmiah ki
        JOIN academic_tempprogramstudi tps ON ki.prodi_id = tps.kode
        SET ki.temp_program_studi_id = tps.id;

        UPDATE academic_kelas k
        JOIN academic_tempprogramstudi tps ON k.prodi_id = tps.kode
        SET k.temp_program_studi_id = tps.id;

        UPDATE academic_pemberitahuanprodi pp
        JOIN academic_tempprogramstudi tps ON pp.prodi_id = tps.kode
        SET pp.temp_program_studi_id = tps.id;

        UPDATE academic_staffprodi sp
        JOIN academic_tempprogramstudi tps ON sp.prodi_id = tps.kode
        SET sp.temp_program_studi_id = tps.id;
        ''')
        

class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0030_dosen_temp_program_studi_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_data)
    ]
