# Generated by Django 4.1.7 on 2023-03-13 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0031_assign_tempprogramstudi_pk_to_prodi_child_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='prodi',
        ),
        migrations.RemoveField(
            model_name='karyailmiah',
            name='prodi',
        ),
        migrations.RemoveField(
            model_name='kelas',
            name='prodi',
        ),
        migrations.RemoveField(
            model_name='pemberitahuanprodi',
            name='prodi',
        ),
        migrations.RemoveField(
            model_name='staffprodi',
            name='prodi',
        ),
        migrations.AlterField(
            model_name='dosen',
            name='temp_program_studi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.tempprogramstudi'),
        ),
        migrations.AlterField(
            model_name='karyailmiah',
            name='temp_program_studi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karya_ilmiah_list', to='academic.tempprogramstudi'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='temp_program_studi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kelas_list', to='academic.tempprogramstudi'),
        ),
        migrations.AlterField(
            model_name='pemberitahuanprodi',
            name='temp_program_studi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemberitahuan_list', to='academic.tempprogramstudi'),
        ),
        migrations.AlterField(
            model_name='staffprodi',
            name='temp_program_studi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_prodi_list', to='academic.tempprogramstudi'),
        ),
    ]
