# Generated by Django 4.1.7 on 2023-03-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0032_remove_program_studi_related_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramStudi',
        ),
    ]
