# Generated by Django 4.1.7 on 2023-03-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0034_rename_tempprogramstudi_programstudi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='temp_program_studi',
            new_name='prodi',
        ),
        migrations.RenameField(
            model_name='karyailmiah',
            old_name='temp_program_studi',
            new_name='prodi',
        ),
        migrations.RenameField(
            model_name='kelas',
            old_name='temp_program_studi',
            new_name='prodi',
        ),
        migrations.RenameField(
            model_name='pemberitahuanprodi',
            old_name='temp_program_studi',
            new_name='prodi',
        ),
        migrations.RenameField(
            model_name='staffprodi',
            old_name='temp_program_studi',
            new_name='prodi',
        ),
    ]
