# Generated by Django 4.1.7 on 2023-03-13 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0035_rename_programstudi_placehoders_to_prodi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstudi',
            name='no_sk',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='programstudi',
            name='tahun_operasional',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='programstudi',
            name='tanggal_sk',
            field=models.DateField(),
        ),
    ]
