# Generated by Django 4.1.7 on 2023-03-14 01:58

from django.db import migrations, connection


def copy_data(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('''
        INSERT INTO academic_tempstaffprodi (no_induk, no_hp, prodi_id, user_id)
        SELECT nip, no_hp, prodi_id, user_id FROM academic_staffprodi;
        ''')


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0037_tempstaffprodi'),
    ]

    operations = [
        migrations.RunPython(copy_data)
    ]
