# Generated by Django 4.1.7 on 2023-03-14 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0038_copy_data_from_staffprodi_to_tempstaffprodi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffProdi',
        ),
    ]
