# Generated by Django 4.1.7 on 2023-03-14 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0041_tempdosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalmakul',
            name='temp_dosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='makul_ajar', to='academic.tempdosen'),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='temp_dosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa_didik', to='academic.tempdosen'),
        ),
    ]
