# Generated by Django 4.1.7 on 2023-03-14 06:30

from django.db import migrations, connection


def copy_data(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('''
        INSERT INTO academic_tempdosen (nip, nama, email, no_hp, gelar, prodi_id)
        SELECT nip, nama, email, no_hp, gelar, prodi_id FROM academic_dosen;
        ''')


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0042_jadwalmakul_temp_dosen_mahasiswa_temp_dosen'),
    ]

    operations = [
        migrations.RunPython(copy_data)
    ]
