# Generated by Django 4.1.7 on 2023-03-14 06:38

from django.db import migrations, connection


def assign_data(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('''
        UPDATE academic_mahasiswa m
        JOIN academic_tempdosen td ON m.pembimbing_akademik_id = td.nip
        SET m.temp_dosen_id = td.id;

        UPDATE academic_jadwalmakul jm
        JOIN academic_tempdosen td ON jm.dosen_id = td.nip
        SET jm.temp_dosen_id = td.id;
        ''')


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0043_copy_data_from_dosen_to_temp_dosen'),
    ]

    operations = [
        migrations.RunPython(assign_data)
    ]
