# Generated by Django 4.1.7 on 2023-03-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0044_assign_tempdosen_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwalmakul',
            name='dosen',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='pembimbing_akademik',
        ),
        migrations.DeleteModel(
            name='Dosen',
        ),
    ]
