# Generated by Django 4.1.7 on 2023-03-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0045_remove_jadwalmakul_dosen_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempDosen',
            new_name='Dosen',
        ),
        migrations.RenameField(
            model_name='jadwalmakul',
            old_name='temp_dosen',
            new_name='dosen',
        ),
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='temp_dosen',
            new_name='pembimbing_akademik',
        ),
    ]
