# Generated by Django 4.1.7 on 2023-03-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0047_mahasiswa_tahun_angkatan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upttik',
            options={'verbose_name_plural': 'UPT TIK'},
        ),
    ]
