# Generated by Django 4.1.7 on 2023-03-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0048_alter_upttik_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurusan',
            options={'verbose_name_plural': 'Jurusan'},
        ),
    ]
