# Generated by Django 4.1.7 on 2023-03-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0049_alter_jurusan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name_plural': 'Semester'},
        ),
    ]
