# Generated by Django 4.1.7 on 2023-03-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0050_alter_semester_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programpendidikan',
            options={'verbose_name_plural': 'Program Pendidikan'},
        ),
    ]
