# Generated by Django 4.1.7 on 2023-03-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0051_alter_programpendidikan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gedungkuliah',
            options={'verbose_name_plural': 'Gedung Kuliah'},
        ),
    ]
