# Generated by Django 4.1.7 on 2023-03-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0053_alter_pemberitahuan_options_alter_pemberitahuan_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemberitahuan',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='academic/files/'),
        ),
        migrations.AlterField(
            model_name='pemberitahuan',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
