# Generated by Django 4.1.7 on 2023-03-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0054_alter_pemberitahuan_file_alter_pemberitahuan_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programstudi',
            options={'verbose_name_plural': 'Program Studi'},
        ),
    ]
