# Generated by Django 4.1.7 on 2023-03-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0055_alter_programstudi_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprodi',
            options={'verbose_name_plural': 'Staff Prodi'},
        ),
    ]
