# Generated by Django 4.1.7 on 2023-03-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0056_alter_staffprodi_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='academic/images/'),
        ),
    ]
