# Generated by Django 4.1.7 on 2023-03-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0057_dosen_foto_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosen',
            options={'verbose_name_plural': 'Dosen'},
        ),
    ]
