# Generated by Django 4.1.7 on 2023-03-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0058_alter_dosen_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kelas',
            options={'verbose_name_plural': 'Kelas'},
        ),
    ]
