# Generated by Django 4.1.7 on 2023-03-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0059_alter_kelas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mahasiswa',
            options={'verbose_name_plural': 'Mahasiswa'},
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
