# Generated by Django 4.1.7 on 2023-03-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0060_alter_mahasiswa_options_alter_mahasiswa_foto_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='academic/images/'),
        ),
    ]
