# Generated by Django 4.1.7 on 2023-03-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0061_alter_mahasiswa_foto_profil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruangan',
            options={'verbose_name_plural': 'Ruangan'},
        ),
    ]
