# Generated by Django 4.1.7 on 2023-03-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0063_alter_aduanruangan_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aduanruangan',
            options={'verbose_name_plural': 'Aduan Ruangan'},
        ),
    ]
