# Generated by Django 4.1.7 on 2023-03-23 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0064_alter_aduanruangan_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyailmiah',
            name='mahasiswa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karya_ilmiah_list', to='academic.mahasiswa'),
        ),
    ]
