# Generated by Django 4.1.7 on 2023-03-23 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0065_alter_karyailmiah_mahasiswa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karyailmiah',
            options={'verbose_name_plural': 'Karya Ilmiah'},
        ),
    ]
