# Generated by Django 4.1.7 on 2023-03-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0066_alter_karyailmiah_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwal',
            options={'verbose_name_plural': 'Jadwal'},
        ),
    ]
