# Generated by Django 4.1.7 on 2023-03-24 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0067_alter_jadwal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='program_studi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='list_makul', to='academic.programstudi'),
            preserve_default=False,
        ),
    ]
