# Generated by Django 4.1.7 on 2023-03-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0068_matakuliah_program_studi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matakuliah',
            options={'verbose_name_plural': 'Mata Kuliah'},
        ),
    ]
