# Generated by Django 4.1.7 on 2023-03-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0069_alter_matakuliah_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwalmakul',
            options={'verbose_name_plural': ''},
        ),
    ]
