# Generated by Django 4.1.7 on 2023-03-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0070_alter_jadwalmakul_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khs',
            options={'verbose_name_plural': 'KHS'},
        ),
    ]
